import type { ArenaSession, Finding, Verdict, Severity, PrSummary } from "../lib/types";

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

function severityEmoji(s: Severity): string {
  switch (s) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    case "low": return "🔵";
    case "info": return "⚪";
  }
}

export function generateMarkdownReport(
  session: ArenaSession,
  findings: Finding[],
  verdict: Verdict,
  dismissedCount = 0,
  summary?: PrSummary,
  rejectedByVerifier = 0
): string {
  const lines: string[] = [];

  if (session.mode === "pr") {
    lines.push(`# PR Review: ${session.prTitle ?? `#${session.prNumber ?? ""}`}`);
    lines.push("");
    if (session.prNumber !== undefined && session.prUrl) {
      lines.push(`**PR:** [#${session.prNumber}](${session.prUrl})`);
    }
    if (session.prAuthor) {
      lines.push(`**Author:** ${session.prAuthor}`);
    }
  } else {
    lines.push(`# Ref Review: ${session.repoOwner}/${session.repoName}`);
    lines.push("");
    lines.push(`**Base:** \`${session.baseRef}\` (\`${session.baseSha.slice(0, 7)}\`)`);
    lines.push(`**Head:** \`${session.headRef}\` (\`${session.headSha.slice(0, 7)}\`)`);
  }
  lines.push(`**Reviewers:** ${session.selectedRoles.join(", ")}`);
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // PR Summary
  if (summary) {
    lines.push("## Summary");
    lines.push("");
    lines.push(summary.overview);
    if (summary.keyChanges.length > 0) {
      lines.push("");
      lines.push("### Key Changes");
      lines.push("");
      for (const c of summary.keyChanges) {
        lines.push(`- ${c}`);
      }
    }
    if (summary.hotspotFiles.length > 0) {
      lines.push("");
      lines.push("### Hotspot Files");
      lines.push("");
      for (const f of summary.hotspotFiles) {
        lines.push(`- \`${f}\``);
      }
    }
    lines.push("");
  }

  // Verdict summary
  lines.push("## Verdict");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Risk Score | **${verdict.riskScore}/100** |`);
  lines.push(`| Recommendation | **${verdict.mergeRecommendation.replace(/_/g, " ")}** |`);
  if (rejectedByVerifier > 0) {
    lines.push(`| Rejected by verifier | ${rejectedByVerifier} |`);
  }
  if (dismissedCount > 0) {
    lines.push(`| Findings accepted | ${findings.length} |`);
    lines.push(`| Findings dismissed | ${dismissedCount} |`);
  }
  lines.push("");
  lines.push(verdict.summary);
  lines.push("");

  // Blockers
  if (verdict.blockers.length > 0) {
    lines.push("## Blockers");
    lines.push("");
    for (const b of verdict.blockers) {
      lines.push(`### ${severityEmoji(b.severity)} ${b.title}`);
      lines.push("");
      lines.push(b.description);
      if (b.filePath) {
        lines.push("");
        lines.push(`**File:** \`${b.filePath}${b.lineStart ? `:${b.lineStart}` : ""}\``);
      }
      if (b.evidence) {
        lines.push("");
        lines.push("```");
        lines.push(b.evidence);
        lines.push("```");
      }
      lines.push("");
      lines.push(`**Recommendation:** ${b.recommendation}`);
      lines.push("");
    }
  }

  // All findings by severity
  lines.push("## All Findings");
  lines.push("");

  const sorted = [...findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );

  for (const f of sorted) {
    const location = f.filePath
      ? ` — \`${f.filePath}${f.lineStart ? `:${f.lineStart}` : ""}\``
      : "";
    const adjusted =
      f.originalSeverity
        ? ` *(was ${f.originalSeverity})*`
        : "";
    lines.push(
      `- ${severityEmoji(f.severity)} **${f.severity.toUpperCase()}**${adjusted} [${f.reviewerRole}] ${f.title}${location}`
    );
    lines.push(`  ${f.description}`);
    if (f.verifierNote) {
      lines.push(`  *Verifier:* ${f.verifierNote}`);
    }
    lines.push(`  *Recommendation:* ${f.recommendation}`);
    lines.push("");
  }

  // Suggested commits
  if (verdict.suggestedCommits.length > 0) {
    lines.push("## Suggested Commits");
    lines.push("");
    for (const c of verdict.suggestedCommits) {
      lines.push(`- \`${c}\``);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Nitpick*");
  lines.push("");

  return lines.join("\n");
}
